# SPDX-License-Identifier: MIT
"""gen_tensors.py — generate tensors.h from a .base bundle's JSON header.

Usage: python3 gen_tensors.py model.base > tensors.h

Scaffolding for qwen3_base.c until a runtime header parser lands.
Offsets are copied verbatim from the header; scale/bias offsets are
tensor-relative (see FORMAT.md).
"""
import json
import struct
import sys


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: gen_tensors.py model.base")
    with open(sys.argv[1], "rb") as f:
        magic = f.read(4)
        if magic != b"BASE":
            sys.exit("bad magic: not a .base file")
        (version,) = struct.unpack("<I", f.read(4))
        (hlen,) = struct.unpack("<Q", f.read(8))
        header = json.loads(f.read(hlen))

    tensors = header["tensors"]
    print("#pragma once")
    print("/* generated by gen_tensors.py — do not edit */")
    print("typedef struct { const char *name; int is_q4;"
          " long off, soff, boff; int rows, cols; } BTensor;")
    print("static const BTensor BT[] = {")
    for t in tensors:
        shape = t["shape"]
        rows = shape[0]
        cols = shape[1] if len(shape) > 1 else 1
        if t.get("scale_dtype") not in (None, "bf16"):
            sys.exit(f"tensor {t['name']}: scale_dtype "
                     f"{t['scale_dtype']} not supported (bf16 only)")
        print('  {"%s", %d, %dL, %dL, %dL, %d, %d},' % (
            t["name"], 1 if t["dtype"] == "base_q4" else 0,
            t["offset"], t.get("scale_offset") or -1,
            t.get("bias_offset") or -1, rows, cols))
    print("};")
    print(f"#define BT_COUNT {len(tensors)}")


if __name__ == "__main__":
    main()
