# SPDX-License-Identifier: MIT
"""gen_tensors.py — generate tensors.h from a .base bundle's JSON header.

Usage: python3 gen_tensors.py model.base > tensors.h

Scaffolding for qwen3_base.c until a runtime header parser lands.
Offsets are copied verbatim from the header; scale/bias offsets are
tensor-relative (see FORMAT.md).
"""
import json
import struct
import sys


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: gen_tensors.py model.base")
    with open(sys.argv[1], "rb") as f:
        magic = f.read(4)
        if magic != b"BASE":
            sys.exit("bad magic: not a .base file")
        (version,) = struct.unpack("<I", f.read(4))
        (hlen,) = struct.unpack("<Q", f.read(8))
        header = json.loads(f.read(hlen))

    tensors = header["tensors"]
    cfg = header["config"]
    blob = (16 + hlen + 0xFFFF) & ~0xFFFF
    print("#pragma once")
    print("/* generated by gen_tensors.py — do not edit */")
    print(f"#define BLOB_OFF 0x{blob:x}UL")
    print(f"#define HIDDEN   {cfg['hidden_size']}")
    print(f"#define NLAYERS  {cfg['num_hidden_layers']}")
    print(f"#define NQH      {cfg['num_attention_heads']}")
    print(f"#define NKVH     {cfg['num_key_value_heads']}")
    print(f"#define HDIM     {cfg['head_dim']}")
    print(f"#define FFN      {cfg['intermediate_size']}")
    print(f"#define VOCAB    {cfg['vocab_size']}")
    print(f"#define RMS_EPS  {cfg['rms_norm_eps']}f")
    print(f"#define ROPE_TH  {cfg['rope_theta']}f")
    eos = cfg.get("eos_token_ids") or [cfg.get("eos_token_id", -1)]
    eos = list(dict.fromkeys(eos + [cfg.get("eos_token_id", -1)]))[:2]
    while len(eos) < 2:
        eos.append(-1)
    print(f"#define EOS0     {eos[0]}")
    print(f"#define EOS1     {eos[1]}")
    print("typedef struct { const char *name; int is_q4;"
          " long off, soff, boff; int rows, cols, sdt16; } BTensor;")
    print("static const BTensor BT[] = {")
    for t in tensors:
        shape = t["shape"]
        rows = shape[0]
        cols = shape[1] if len(shape) > 1 else 1
        sdt = t.get("scale_dtype")
        if sdt not in (None, "bf16", "f16"):
            sys.exit(f"tensor {t['name']}: scale_dtype "
                     f"{sdt} not supported (bf16/f16 only)")
        print('  {"%s", %d, %dL, %dL, %dL, %d, %d, %d},' % (
            t["name"], 1 if t["dtype"] == "base_q4" else 0,
            t["offset"], t.get("scale_offset") or -1,
            t.get("bias_offset") or -1, rows, cols,
            1 if sdt == "f16" else 0))
    print("};")
    print(f"#define BT_COUNT {len(tensors)}")


if __name__ == "__main__":
    main()
